version: '3.8'

services:
  phonebook_api:
    build: .
    container_name: phonebook-web-server
    ports:
      - "${API_PORT}:80"
    env_file:
      - .env
    networks:
      - phonebook-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: phonebook-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:5432"
    networks:
      - phonebook-network


networks:
  phonebook-network:
    driver: bridge
